### ISSUE TITLE
RuntimeError: asyncio.run() Conflict When Executing 'run_sync' Example in Jupyter Issue with Example Code Execution in Jupyter Lab: asyncio RuntimeError

### ISSUE THREAD

**Issue by MUKESHRAJMAHENDRAN** [pydantic/pydantic-ai#114]
```py
from pydantic_ai import Agent, RunContext
from pydantic_ai.models.openai import OpenAIModel

model = OpenAIModel('gpt-4o', api_key=api_key)



roulette_agent = Agent(  
    model=model,
    deps_type=int,
    result_type=bool,
    system_prompt=(
        'Use the `roulette_wheel` function to see if the '
        'customer has won based on the number they provide.'
    ),
    
)


@roulette_agent.tool
async def roulette_wheel(ctx: RunContext[int], square: int) -> str:  
    """check if the square is a winner"""
    return 'winner' if square == ctx.deps else 'loser'


# Run the agent
success_number = 18  
result = roulette_agent.run_sync('Put my money on square eighteen', deps=success_number)
print(result.data)  
#> True

result = roulette_agent.run_sync('I bet five is the winner', deps=success_number)
print(result.data)
#> False
```

![Screenshot 2024-12-02 200119](https://github.com/user-attachments/assets/f200409c-a24b-4261-81ac-5c11e028a162)

**Comment by samuelcolvin** [comment]
ye, if you're inside a running event loop, you'll need to use `await agent.run()`.

maybe we could add an even more explicit error.

**Comment by MUKESHRAJMAHENDRAN** [comment]
Thanks for the response,

from pydantic_ai import Agent

agent = Agent(model=model)

result_sync = agent.run_sync('What is the capital of Italy?')
print(result_sync.data)
#> Rome


async def main():
    result = await agent.run('What is the capital of France?')
    

---
Every Example is working fine when we run as python file but not running while running in jupyter lab cells

**Comment by samuelcolvin** [comment]
It makes your code much easier to read if you format code as python.

If Jupyter runs code inside an async context, you'll need to use `await agent.run(...)`, not `agent.run_sync(...)` everywhere.
