### ISSUE TITLE
Support StructuredTool

### ISSUE THREAD

**Issue by lgesuellip** [pydantic/pydantic-ai#121]
Hi Team,

At Pampa, we're currently testing a new framework and need to implement a StructuredTool class, similar to LangChain's [StructuredTool](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/tools/structured.py#L32). This class would encapsulate any function, allowing it to be used seamlessly by an agent while maintaining a clear input/output schema (BaseModel).

Our goal is to use this to wrap the tool definitions for an API. By defining clear input and output schemas, we’re creating a structured and standardized approach for interacting with the API. You can see this in the following example, we have a generic function and we have available the schemas.

```py
def tool_util(client, tool_id):

  # Wrapper function to execute
  def tool_wrapper(*args, **kwargs):
    response = client.tools.execute(
      tool_name=tool_id,
      inputs=kwargs,
    )
    return response

  # Get tool definition
  tool_def = client.tools.get(tool_id=tool_id)

  # Create and return the structured tool
  return StructuredTool.from_function(
    func=tool_wrapper,
    name=tool_name,
    description=description,
    args_schema=args_schema
  )
```

Currently, I am exploring the implementation by inheriting from the [Tool](https://github.com/pydantic/pydantic-ai/blob/main/pydantic_ai_slim/pydantic_ai/_tool.py#L20) class. Do you have any recommendations or best practices for implementing this functionality?

Thanks,

**Comment by samuelcolvin** [comment]
Hi @lgesuellip, you don't need to inherit from `Tool`, especially as it's currently private and it's signature may change.

As part of #110 I'm intending to expose `Tool` as a reusable wrapper for tools, but until then, I think you can just create functions and reuse them, e.g.

```py
async def my_tool(a: int, b: str) -> str:
    return f'{a}<>{b}'

agent1 = Agent()
agent1.tool(my_tool)

agent2 = Agent()
agent2.tool(my_tool)
```

**Comment by lgesuellip** [comment]
Thank you @samuelcolvin , it looks promising!
