### ISSUE TITLE
How to dynamically unload tools?

### ISSUE THREAD

**Issue by pedroallenrevez** [pydantic/pydantic-ai#125]
We can `agent.tool` but how to unload them?
The objective is to have fine-grained control over what tools are possible to choose according to user query.

**Comment by samuelcolvin** [comment]
ye, we've discussed this, it would also be useful if the description for a tool could be dynamic (generated per LLM call by a function). So maybe w can combine the two.

**Comment by pedroallenrevez** [comment]
Yes please, exactly that. And also to be able to select which tool to use, in case a user wants a specific tool.

**Comment by samuelcolvin** [comment]
This was solved by #157, sorry I forgot to link the PR.
