### ISSUE TITLE
Question about result aliases

### ISSUE THREAD

**Issue by voberoi** [pydantic/pydantic-ai#132]
Is it possible to use Pydantic aliases to do the following?

1. Retain the same attribute name in my Python code
2. Change the attribute name serialized in the JSON schema for a tool call

A basic example from your docs. Let's say I have:

```
class Box(BaseModel):
    width: int
    height: int
    depth: int
    units: str
 ```
 
 ... and I find that "measurement_units" leads to better results in the LLM call, so I change that field name:
 
 ```
 class Box(BaseModel):
    # ... all other fields remain the same
    measurement_units: str
 ```
 
 Is there a way to continue referring to the field as `units` in my code while serializing the field as `measurement_units` in the LLM call?
 
 I find this sort of thing is common while iterating, and aliases makes things easier if the object is wired up to the rest of the app somehow.

**Comment by samuelcolvin** [comment]
Yes, this works out of the box, you just need to use the [alias functionality from Pydantic](https://docs.pydantic.dev/latest/concepts/alias/):

```py
from openai import BaseModel
from pydantic import Field

import pydantic_ai


class Box(BaseModel):
    width: int
    height: int
    depth: int
    units: str = Field(validation_alias='measurement_units')


a = pydantic_ai.Agent(model='openai:gpt-4o', result_type=Box)

result = a.run_sync('the box is 3x4x5 inches')
print(result.data)
```

**Comment by voberoi** [comment]
Amazing, thank you.
