### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by jacobweiss2305** [pydantic/pydantic-ai#133]
Hey Team,

Fantastic job. A few points of feedback:

- I dont think you should include all model providers in the initial dependencies. For example when I pip install pydantic-ai, i shouldn't see openai, google, and groq. Instead you should let the developers pick which dependencies to manually install. 

- Do we need requests and httpx? I think we can just standardize to httpx.

- Same with logfire. This should be a choice by the developer to include this, and not automatically included in the dependencies.

**Comment by samuelcolvin** [comment]
Please read https://ai.pydantic.dev/install/#slim-install

**Comment by jacobweiss2305** [comment]
Thank you @samuelcolvin. This is exactly what I was looking for.

**Comment by samuelcolvin** [comment]
Just to confirm, even when installing `pydantic-ai`, `logfire` is not installed, just the `logfire-api` package which provides no-op stubs to allow optional use of logfire.

To install logfire, use `pip install 'pydantic-ai[logfire]` or `pip install 'pydantic-ai-slim[logfire]`.

**Comment by jacobweiss2305** [comment]
I love this so much. Thanks again @samuelcolvin. Can't wait for Bedrock and Anthropic
