### ISSUE TITLE
Support of Mistral

### ISSUE THREAD

**Issue by YanSte** [pydantic/pydantic-ai#146]
Hi,

Thank you so much for creating this framework!

It’s incredibly well-structured, especially when compared to others, and impressively lightweight. I absolutely love it.

I was wondering if there’s any possibility of adding support for Mistral?

Thanks again for your excellent work.,

**Comment by samuelcolvin** [comment]
Happy to accept a pr to add support for mistral.

If they have an openai compatible API, it should be pretty simple.

Out of interest, why do you want mistral? If it's about data staying in the EU, you might find vertex AI model useful.

**Comment by YanSte** [comment]
Yes, it's about data staying in the EU. RGPD.

Super, I will have a look. When is done I will create a PR to help.

Thanks.

**Comment by YanSte** [comment]
Close 💌
