### ISSUE TITLE
Support LiteLLM

### ISSUE THREAD

**Issue by ndilsou** [pydantic/pydantic-ai#152]
[LiteLLM](https://docs.litellm.ai/docs/) gives you most if not all the providers through one API. You could even imagine centralizing on this one library to be able to focus your attention on the higher value added features you want to add to the library instead of running after each individual LLM API provider separately.

**Comment by pedroallenrevez** [comment]
@ndilsou 
I would definitely recommend against litellm, I mean just look at their repo for one minute. It's extremely non-pydantic, and their poor typing would create nightmares for the type-guardians of the python ecossystem.

**Comment by laxas** [comment]
What about https://github.com/andrewyng/aisuite ? That seems more lightweight but would also enable a variety of models at once.

**Comment by samuelcolvin** [comment]
Putting it politely, it looks like aisuite will suffer from the same drawbacks @pedroallenrevez mentioned about litellm.

**Comment by samuelcolvin** [comment]
I think on balance it would be a mistake to support LiteLLM right now.

Closing this, but happy to re-open if I'm wrong.

**Comment by s4v4g3** [comment]
Given that many LiteLLM-proxied models pretty much work out of the box using the instructions [here](https://ai.pydantic.dev/models/#openai-compatible-models), I don't see much value in providing explicit support for LiteLLM.  
I did get a laugh reading the comments above.  "Non-pydantic" is being very polite.
