### ISSUE TITLE
Is that an alternative to popular `guidance` or they can work together?

### ISSUE THREAD

**Issue by pySilver** [pydantic/pydantic-ai#158]
Thanks for your lib! It looks very interesting. I'm wondering if that is possible to use it with https://github.com/guidance-ai/guidance as latter is great in response shaping or you aim to replace that lib too?

**Comment by pySilver** [comment]
After some consideration I think my question is `apple vs oranges` type.

**Comment by samuelcolvin** [comment]
I think I agree it's just a different way of building with LLMs, happy to consider a specific case where we use or that library or learn from it.

**Comment by samuelcolvin** [comment]
Closing, but happen to reopen if there's something concrete we can do.
