### ISSUE TITLE
How to work with the model that does not support tools?

### ISSUE THREAD

**Issue by pySilver** [pydantic/pydantic-ai#160]
Simple example causes error:

```
BadRequestError: Error code: 400 - {'error': {'message': 'gemma2:9b-text-q4_K_M does not support tools', 'type': 'api_error', 'param': None, 'code': None}}
```

```python
from pydantic_ai import Agent
from pydantic import BaseModel
from openai import AsyncOpenAI
from pydantic_ai.models.openai import OpenAIModel


class CityLocation(BaseModel):
    city: str
    country: str


client = AsyncOpenAI(
    base_url='http://localhost:11434/v1',
    api_key='your-api-key',
)

model = OpenAIModel('gemma2:9b-text-q4_K_M', openai_client=client)
agent = Agent(model, result_type=CityLocation)

result = await agent.run('Where the olympics held in 2012?')
print(result.data)
#> city='London' country='United Kingdom'
print(result.cost())
#> Cost(request_tokens=56, response_tokens=8, total_tokens=64, details=None)
```

Not sure what to do and even if it has to be supported?

**Comment by samuelcolvin** [comment]
Well, I guess if the model is able to return structured responses of some kind, you could implement a custom `Model` which somehow parses the response and builds instances of [`ModelStructuredResponse`](https://ai.pydantic.dev/api/messages/#pydantic_ai.messages.ModelStructuredResponse) to return.

Does that answer your question?

**Comment by sydney-runkle** [comment]
Going to close this for now. Happy to reopen if folks have follow up inquiries.

**Comment by grahamannett** [comment]
hey @samuelcolvin seems like a lot of the pydantic-ai API/info has changed in the past 1-2 months, if a model is able to return structured response but it follows something like the r1 <think> tags, is there a standardized way to use that?  I dont see `ModelStructuredResponse` as part of the docs anymore and doesnt seem like using result_type with r1 models works at all.

**Comment by pySilver** [comment]
It would be cool if https://github.com/boundaryml/baml could be integrated. It's simply awesome and removes the need for tooling support at all.
