### ISSUE TITLE
Dynamic User Context in AI Agent Interactions

### ISSUE THREAD

**Issue by zby** [pydantic/pydantic-ai#163]
In the current PydanticAI example for a bank support agent (https://github.com/pydantic/pydantic-ai/blob/main/pydantic_ai_examples/bank_support.py), the `customer_id` is hardcoded:

```python
deps = SupportDependencies(customer_id=123, db=DatabaseConn())
```
However, in real-world web applications, the customer_id is typically dynamically retrieved after user authentication
and saved in a user session.

What are the recommended patterns for dynamically injecting user-specific context into AI agents?

### General overview of the problem based on web applications:

There are three critical context layers in web applications. They contain data that can be initialized at specific phases
of the application lifecycle.

1. Application Server Startup Context (Global/Static Resources)
* Database connection pools
* Configuration settings
* Shared service clients
* Authentication and authorization providers

2. Session Context (User-Specific Persistent Data)
* User ID after authentication
* User preferences
* Shopping cart contents
* Previous interaction history

3. HTTP Request Context
* Current request parameters
* Form submissions
* Query parameters
* Authentication tokens
* IP address
* User agent information

Currently the support agent object is created in the first initialization phase, but the database connection is passed to it only at the user query time - together with the user name (which would normally be initialized from the session data) and the current user query.

**Comment by samuelcolvin** [comment]
The whole point of the dependency system is that you can  create and pass the dependencies within the request not in at module import time (what you call "Application Server Startup Context (Global/Static Resources)").

Unless I'm missing something, this is a solve problem.
