### ISSUE TITLE
Proper error handling of tool calls

### ISSUE THREAD

**Issue by schatimo** [pydantic/pydantic-ai#167]
Thanks for the great package! With this issue I would like to propose that errors raised from a tool call should be properly handled to be further processed by the LLM.
E.g., running the following script using Ollama results in a `ValueError` that is not properly handled by the agent.

```python
from pydantic_ai import Agent, RunContext
from pydantic_ai.models.openai import OpenAIModel
from openai import AsyncOpenAI
from dataclasses import dataclass


@dataclass
class Deps:
    pass


client = AsyncOpenAI(base_url="http://localhost:11434/v1", api_key="does not matter")
model = OpenAIModel(model_name="llama3.2:latest", openai_client=client)
agent = Agent(model, system_prompt="Be concise, reply with one sentence.")


@agent.tool
def get_user_name(ctx: RunContext[Deps], user_id: int) -> str:
    """Takes the unique id of a user and returns the name of the user.

    Args:
        user_id: a unique id of a user

    Returns:
        user_name: the name of the user

    Raises:
        ValueError: when the user id does not exist
    """
    pseudo_db: dict[int, str] = {1: "John F. Kennedy", 2: "George Washington"}
    try:
        user_name: str = pseudo_db[user_id]
    except KeyError:
        raise ValueError(f"There is no user with the id {user_id} in the database.")
    return user_name


result = agent.run_sync("What is the name of the user with user id 2?")
print(result.data)
# Returns: The user with ID 2 is George Washington.
result = agent.run_sync("What is the name of the user with id 123?")
print(result.data)
# Raises a ValueError as expected but does not return the error message as a string
```

Thus, such that `result = agent.run_sync("What is the name of the user with id 123?")` returns a `str`, I would propose to change https://github.com/pydantic/pydantic-ai/blob/6201af4dc8130aeb9ee81d073bae98d02acdb709/pydantic_ai_slim/pydantic_ai/agent.py#L202 to
```python
try:
    either = await self._handle_model_response(model_response, deps)
except Exception as exc:
    either = _MarkFinalResult(exc.__str__())
```
Then, the iteration of tool calls stops and the error message is taken as final result to be processed by the LLM returning a string.

**Comment by samuelcolvin** [comment]
I'm strongly in favor of not returning arbitrary errors to the model, we already have the [`ModelRetry`](https://ai.pydantic.dev/api/exceptions/#pydantic_ai.exceptions.ModelRetry) exception to send a message back to the model.

If we need other specific exceptions, we can add those.

We should also properly support Pydantic function validators, which allow you to raise `ValueError`. See #151.
