### ISSUE TITLE
Registering a bounded function as a tool - a brainstorming idea

### ISSUE THREAD

**Issue by zby** [pydantic/pydantic-ai#168]
RunContext is a special parameter for the tool functions. It is treated in special ways - just like the first parameter to a method. I think it would be elegant if you could register a bounded method as a tool. This way you could start with a class managing your state - just like you do for web applications and register methods from it as the agent tools. For example taking your banking support example - you could have a `Banking` object based on some Object Relational Mapper representing a banking database with a `get_customer_name(id: int)` method and you could register that method (bound to the banking database).

You can have a look at https://github.com/zby/LLMEasyTools/blob/main/examples/stateful_search.py as an example code using that idea.

This is related to: https://github.com/pydantic/pydantic-ai/issues/163

**Comment by zby** [comment]
Here is what ChatGPT o1 thinks about my idea: https://chatgpt.com/share/675422c0-bf08-8008-936e-99bf1cefd615

**Comment by samuelcolvin** [comment]
The way to do this is to pass your class as a dependency, then access it via `RunContext` and call the bound method. 

There's an example (albeit for dynamic system prompt, not tools, but the same rules apply) here: https://ai.pydantic.dev/testing-evals/#measuring-performance
