### ISSUE TITLE
Invalid JSON Schema for OpenAI

### ISSUE THREAD

**Issue by lemeb** [pydantic/pydantic-ai#172]
Hi all,

Consider [this](https://gist.github.com/lemeb/f1e157c9516af8f1c8a63cd593271326):

```diff
# from https://ai.pydantic.dev/examples/weather-agent/
@weather_agent.tool
async def get_weather(
-    async def get_weather(ctx: RunContext[Deps], lat: float, lng: float) -> dict[str, Any]:
+    async def get_weather(ctx: RunContext[Deps], lat_lng: tuple[float, float]) -> dict[str, Any]:
) -> dict[str, Any]:
    """Get the weather at a location.

    Args:
        ctx: The context.
-        lat: Latitude of the location.
-        lng: Longitude of the location.
+        lat_lng: The latitude and longitude of the location.
+    """
+     lat, lng = lat_lng
    if ctx.deps.weather_api_key is None:
```

(You can copy-paste the modified code [here](https://gist.github.com/lemeb/f1e157c9516af8f1c8a63cd593271326))

This will make OpenAI's API fail:

```
  File "/Users/l/Library/Caches/uv/archive-v0/IrhvUPHYED9V5EcCUkM5d/lib/python3.11/site-packages/openai/_base_client.py", line 1638, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'get_weather': In context=('properties', 'lat_lng'), array schema missing items.", 'type': 'invalid_request_error', 'para
m': 'tools[1].function.parameters', 'code': 'invalid_function_parameters'}}
```

I think this is because the JSON schema that is generated by Pydantic for the function is this:

```json
{
   "description":"Get the weather at a location.",
   "properties":{
      "lat_lng":{
         "description":"The latitude and longitude of the location.",
         "maxItems":2,
         "minItems":2,
         "prefixItems":[
            {
               "type":"number"
            },
            {
               "type":"number"
            }
         ],
         "title":"Lat Lng",
         "type":"array"
      }
   },
   "required":[
      "lat_lng"
   ],
   "type":"object",
   "additionalProperties":false
}
```

Alas, OpenAI [supports only a subset](https://platform.openai.com/docs/guides/structured-outputs#supported-schemas) of JSONSchema.

Now, looking at your Gemini code, it looks like you're aware of this, but I'm wondering if you're planning on making more comprehensive JSONSchema reformatting to ensure that such scenarios are handled. For what it's worth, I'm also working on something like this, so let me know if you want to chat... :)

**Comment by samuelcolvin** [comment]
I don't see how this can be handled in a general way. 

In some cases we can report an error before making the request, but that would be very annoying if:
* We made a mistake and raised an error for a valid case
* OpenAI released an update that fixed something, but we still raised an error
* Someone wanted to use the OpenAI model for any of the other models that have OpenAI compatibility, but support more JSON Schema

We can probably make the error slightly more descriptive, but I don't see what else we can do.

**Comment by samuelcolvin** [comment]
@lemeb let me know if you have proposal to create a JSON Schema for `tuple[float, float]` that openAI will accept? Otherwise I propose we close this.

**Comment by samuelcolvin** [comment]
Thanks for understanding, the typeddict solution would work, but would be hard to do in a general way with Pydantic.

Yes, pr to improve the docstrings would be great please.
