### ISSUE TITLE
Agents generate a broken message history with structured responses

### ISSUE THREAD

**Issue by jlowin** [pydantic/pydantic-ai#174]
If an agent uses a structured result type, then the final message produced is a tool call, but without a corresponding tool result. This creates an issue if the message history is passed to another agent call. With OpenAI, it results in the following error: `"An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'.`

If the result type is `str`, then this isn't an issue because no tool call is generated.

Here is an example that demonstrates this. A structured response is generated, and then its messages are used as the input history to a second response, which fails. 

```python
import pydantic_ai
from pydantic import BaseModel

class Demo(BaseModel):
    x: int
    
    
agent = pydantic_ai.Agent(model='openai:gpt-4o', result_type=Demo)

# first call
response = await agent.run('set x to any number between 1 and 100')

# second call, errors
await agent.run('set x to 5 more than the last value of x', message_history=response.new_messages())
```

**Comment by jlowin** [comment]
The latter option is sufficient - add a virtual tool response, either blank or confirmatory as you suggest.

**Comment by sudoskys** [comment]
Openai requires that ToolCall and tool responses must be paired and adjacent.
When used, they may need to be treated as a group to bind and rearrange

Here is how I did: https://github.com/LlmKira/Openaibot/blob/main/app/middleware/llm_task.py#L32-L114
Hope this can provide some help
