### ISSUE TITLE
When using result.stream_text(delta=True) result.all_messages() does not contain the model's response

### ISSUE THREAD

**Issue by i-ndigo** [pydantic/pydantic-ai#177]
When using `result.stream_text(delta=True)`, `result.all_messages()` does not contain the model response
# Works as expected

```py
from pydantic_ai import Agent
from dotenv import load_dotenv

load_dotenv()
agent = Agent(
    'openai:gpt-4o',
    system_prompt='Be concise, reply with one sentence.',
)

async def main ():
    async with agent.run_stream('This is a test') as result:
        async for message in result.stream_text():
            pass
        print(result.all_messages())

if __name__ == '__main__':
    import asyncio
    asyncio.run(main())

```
# Does not work

```py
from pydantic_ai import Agent
from dotenv import load_dotenv

load_dotenv()
agent = Agent(
    'openai:gpt-4o',
    system_prompt='Be concise, reply with one sentence.',
)

async def main ():
    async with agent.run_stream('This is a test') as result:
        async for message in result.stream_text(delta=True):
            pass
        print(result.all_messages())

if __name__ == '__main__':
    import asyncio
    asyncio.run(main())

```

**Comment by samuelcolvin** [comment]
@i-ndigo just a side note - it makes issues much easier to understand and respond to if you can format your issues so code is highlighted.

This behaviour is expected, `stream_text(delta=True)` never builds the combined final content, so it can't register the last message, I'll update the documentation to make this explicit.

**Comment by i-ndigo** [comment]
Ahh yes thank you. Forgot to add py to the codeblock to activate the formating sorry.  

Makes sense but it might be a common use case to forward the delta to a client (for fast response) but still wanting to use the message in the backend. With this solution you would need to construct the full response or the delta your self.

**Comment by nathanchapman** [comment]
This no longer appears to be true from my testing. I'm seeing the final response from the LLM returned from `stream_text(delta=True)` as long as you call `result.all_messages()` **_after_** the stream finishes.
This note in the docs confused me though, which is how I ended up here.

Can anyone on the team confirm this was changed? And if so:
- Do you know which version? I couldn't find it in the changelog
- Do we need to get the docs updated to remove this note?
