### ISSUE TITLE
Why use anything else. You have kicked it out of the park.

### ISSUE THREAD

**Issue by Cloudways-AI** [pydantic/pydantic-ai#189]
I have been looking for something that is not just a lot of BS using VS-Code or Anthropic or or or.

I will study this like a bible. Give feed back and share code.

I would like to start a channel with likeminded people. Please let me know your thoughts. I have seen what others can do as a group and it is awesome..

I am retired, so I am looking to re-energise myself. I am too young to put myself out to pasture @ 60. This is the new 40.

**Comment by samuelcolvin** [comment]
Thanks so much. If you're looking for a channel, we have a public slack, see [here](https://ai.pydantic.dev/help/).
