### ISSUE TITLE
Add ability to run initial tool calls before sending the request to the LLM

### ISSUE THREAD

**Issue by eulervoid** [pydantic/pydantic-ai#192]
This looks very promising!

I often run into cases where i want to decide via some python function if the request needs an LLM call or can be processed without the LLM. For this use case, it would be nice to have an option to define tools that get called every time before the first call to the LLM.

Use Cases:
- ending the run early based on some condition, without ever calling the LLM (by using `ctx.end_call` from #142)
- requesting some realtime data to answer requests based on the input (overlaps with `system_prompt`)

Benefits of doing it inside the agent as opposed to before:
- the tool call will automatically become part of the message history and tracing
- all agent behavior is defined within the agent

I could image it to be a decorator, similar to regular tools:

```python
# runs before the first llm call
@agent.init_tool
def preprocess(ctx: RunContext[...], user_prompt: UserPrompt) -> str:
    # end the run early if some condition is met, get some additional context otherwise
    if some_condition(user_prompt.content):
        ctx.end_run("answer")
    else:
        return retrieve_context(user_prompt.content)
```

A good example where this would be useful is a system with multiple choice questions where, if the user picks one of the predefined answers, we can skip the LLM call and act on it straight away.

Or maybe i missed something and there is already a simple way to achieve this?

**Comment by jlowin** [comment]
This seems a little bit like conflating functionality - if there's a function that can be called deterministically, why not call if and then decide whether to call the LLM? Pushing this into the LLM would seem to only hinder your flexibility.

```python
responses = get_multiple_choice()
if should_call_llm(responses):
    await agent.run()
else:
    something_else()
```

or for messages:

```python
responses = get_multiple_choice()
if should_call_llm(responses):
	# build any messages you require, including a UserPrompt(content="The user chose A")
	messages = build_messages(responses)
    await agent.run(message_history=messages)
else:
    something_else()
```

**Comment by samuelcolvin** [comment]
My first instinct is "do it before calling the agent", but I see you've already thought of that.

I'm not completely opposed to this, but I think we would need to see a few other people wanting the feature before we add an extra hook.

One question: is it definitely a good idea to add this to the message history? These won't be real tool calls, could that confuse (or even break) the LLM? e.g. OpenAI has quite strict rules about tools always needing a return value and an ID, if you "invent" a tool call that wasn't really from the model, could it cause any issues.

ROFL, I was about to cc @jlowin, then he replied before me...

**Comment by eulervoid** [comment]
I thought about it a bit more and i think you are right @jlowin, it is cleaner to do it outside the agent. It seems i got a bit carried away with the neatness of having everything in one self-contained agent, but in practice, things like the overall message history are probably going to be managed outside anyways, so feel free to close the issue.

**Comment by jlowin** [comment]
@eulervoid I only speak from experience of trying to push everything into the LLM layer :) I know the feeling!

**Comment by samuelcolvin** [comment]
makes sense, closing.
