### ISSUE TITLE
Memory Implementation

### ISSUE THREAD

**Issue by gsogol** [pydantic/pydantic-ai#196]
Looking for feature parity and enhancements similar to https://docs.phidata.com/agents/memory

1) chat history
2) user memory
3) summaries

great to have short and long term memory ala https://langchain-ai.github.io/langgraph/concepts/memory/

**Comment by dsolito** [comment]
hey!

I impelemented a chat history with a appState deps.
Its a snipet (not the full code)

```
class AppState(BaseModel):
    messages: List[Message] = Field(
        default_factory=list,
        description="Liste des messages de la conversation",
        max_length=1000
    )
    
    def append_messages(self, new_messages: List[Message]) -> None:
        self.messages.extend(new_messages)
        if len(self.messages) > 1000:
            self.messages = self.messages[-1000:]
    
    def clear_messages(self) -> None:
        self.messages.clear()

# Initialize app state
app_state = AppState()



# Initialize the agent with dependencies
agent = Agent(
    "openai:gpt-4o-mini",
    deps_type=AppState,
    result_type=ResponseType,  # type: ignore
    system_prompt=(
        "You are a helpful and friendly AI assistant that can generate images. "
        "When users explicitly request or mention images, use the generate_image tool with detailed prompts. "
        "For regular conversation or questions not related to images, respond with text. "
        "Be helpful and engage naturally in the conversation."
    )
)


@agent.system_prompt
def get_context(ctx: RunContext[AppState]) -> str:
    """Add context about the conversation length if there are previous messages."""
    if ctx.deps.messages:
        return f"This conversation has {len(ctx.deps.messages)} previous messages."
    return "This is the start of our conversation."

async def main(message: cl.Message):
    """Handle incoming messages."""
    result = await agent.run(
        message.content,
        deps=app_state,
        message_history=app_state.messages
    )
    
    app_state.append_messages(result.new_messages())

```
Hopes it helps

**Comment by samuelcolvin** [comment]
There's also https://ai.pydantic.dev/examples/chat-app/.

**Comment by sydney-runkle** [comment]
I feel like maybe it makes sense to close this for now, then?

**Comment by pietz** [comment]
I think that an internal memory or state could actually be a great addition:

- We have a `deps_type`, which is essentially a hidden state that is managed by the user
- We have a `result_type`, which defines the format of the response

The `memory` could be a Pydantic model that is managed by the agent via JSON patches by automatically integrating a tool for it.

For many process automations that I do, such a memory is quite helpful. The agent has the task of collecting certain information from the user, updating the memory along the way. Once it's done, it can use a tool that doesn't require any parameters and store the entire content in the database.
