### ISSUE TITLE
When using Gemini, how can I set attributes available to the "GenerativeModel" class?

### ISSUE THREAD

**Issue by ohmeow** [pydantic/pydantic-ai#197]
`GenerativeModel` accepts a number of attributes such as `generation_config` and `security_settings` ... and so I was wondering how I can set these when creating a Gemini backed agent?

See below
```python
google.generativeai.GenerativeModel(
    model_name: str = 'gemini-1.5-flash-002',
    safety_settings: (safety_types.SafetySettingOptions | None) = None,
    generation_config: (generation_types.GenerationConfigType | None) = None,
    tools: (content_types.FunctionLibraryType | None) = None,
    tool_config: (content_types.ToolConfigType | None) = None,
    system_instruction: (content_types.ContentType | None) = None
)
```

Thanks!

**Comment by samuelcolvin** [comment]
We're going to add support for customizing all models, see #71.

Let's discuss exactly what you need there.

**Comment by jeffbryner** [comment]
Safety settings is a must have since without you are guessing at what gemini will block. 
I'd upvote system_instructions since it is really convenient at model creation to set the system instructions rather than carrying them around in messages, especially if they are lengthy.
