### ISSUE TITLE
How to force the tool output as final output.

### ISSUE THREAD

**Issue by harshdy** [pydantic/pydantic-ai#201]
My tool is fetching the details from the web and formatting it to Json. I want my tool object as final output from the agent, I was wondering is there any method do this.

**Comment by samuelcolvin** [comment]
If you just want a tool which finishes the run, use the `result_type`, see https://ai.pydantic.dev/results/.

If you want to end a run within or after a function tool, see #142

**Comment by samuelcolvin** [comment]
Closing for now as I think that answer your question, but happy to answer more questions, or open.
