### ISSUE TITLE
Extra attributes for logfire's run_span

### ISSUE THREAD

**Issue by fbergamini** [pydantic/pydantic-ai#204]
I would like to pass extra attributes to the run methods that will be included in the logfire's run_span, to better trace agent's run with the same context. I've looked into the code and it seems we could add `extra_log_span_attributes` to the run, run_sync and run_stream methods, like below:

```python
async def run(
        self,
        user_prompt: str,
        *,
        message_history: list[_messages.Message] | None = None,
        model: models.Model | models.KnownModelName | None = None,
        deps: AgentDeps = None,
        infer_name: bool = True,
        extra_log_span_attributes: dict[str, Any] = None,
    ) -> result.RunResult[ResultData]:
```

and then used it on the run_span:

```python
with _logfire.span(
            '{agent_name} run {prompt=}',
            prompt=user_prompt,
            agent=self,
            custom_model=custom_model,
            model_name=model_used.name(),
            agent_name=self.name or 'agent',
        ) as run_span:
            run_span.set_attributes(extra_log_span_attributes)
```

Also, it would be good to have a "Contributing" section (including tests) in the documentation, so I would be able to better contribute with this.

**Comment by samuelcolvin** [comment]
Contributing section make sense (the short answer is, install python, uv, pre-commit, clone, run `make install`, then run `make`)

Regarding the logfire span, can you explain more about your use case?

The general solution would be to either wrap the call in another spans, e.g.

```py
with logfire.spam('whatever ...', ** extra_log_span_attributes):
    agent.run_sync(...)
```

Or to use [OpenTelemetry baggage](https://opentelemetry.io/docs/concepts/signals/baggage/) effectively allows you to add attributes to all spans in a trace. Logfire's SDK doesn't have support for baggage right now, but we're intending to add it soon.

**Comment by samuelcolvin** [comment]
Closing as no response. Happy to help more if there's a follow up.
