### ISSUE TITLE
structured input

### ISSUE THREAD

**Issue by mplemay** [pydantic/pydantic-ai#207]
While many agents are primarily driven by prompts (i.e. `input_type=str`), agents could benefits from structured input (i.e. `input_type=MyPydanticModel`) as well. This functionality would allow agents ingest forms, etc.

**Comment by samuelcolvin** [comment]
you can pass this data as JSON, is it really worth changing the input type and serializing to JSON withint the library?

**Comment by mplemay** [comment]
Thanks for the response, @samuelcolvin! Using `model_dump_json` and passing in the JSON `str` is a viable way to handle this without violating the type constraint. That being said, I believe there are two scenarios where this functionality could add significant value. These are outlined below:

## Case 1
In this example, `agent.run_sync` is guaranteed to call either `thing_2` or `thing_3`, even though `A` contains the "same" field as `B`.

```python
from pydantic import BaseModel, Field

class A(BaseModel):
    c: int = Field(default=0)

class B(BaseModel):
    c: int = Field(default=0)

agent = Agent(input_type=A | B, result_type=float)

@agent.plain_tool
def thing_1(a: A) -> float:
    return a.c + 1

@agent.plain_tool
def thing_2(b: B) -> float:
    return b.c + 1

@agent.plain_tool
def thing_3(c: A | B) -> float:
    return c.c + 2

agent.run_sync(user_prompt=B())
```

## Case 2
In this scenario, the agent utilizes existing fields and generates new ones if a decorator flag (shown below), type annotation, or similar mechanism is present.

```python
from pydantic import BaseModel, Field

class Mixin:
    a: int = Field(default=0, description="field a")

class UserPrompt(BaseModel, Mixin):
    pass

class Input1(BaseModel, Mixin):
    b: float = Field(description="give me another number")

class Input2(BaseModel, Mixin):
    b: bool = Field(description="select either true or false")

agent = Agent(input_type=A, result_type=float)

@agent.plain_tool(generate_missing_fields=True)
def thing_1(inp: Input1) -> float:
    return inp.a + inp.b

@agent.plain_tool(generate_missing_fields=True)
def thing_2(inp: Input2) -> int:
    return inp.a if inp.b else -1
```

## Summary
This feature would offer the following benefits:
- **Prevent hallucinations:** It would stop the LLM from hallucinating, re-inventing variables that already exist, or selecting incompatible functions.
- **Enable model validation:** For example, by leveraging [model validators](https://docs.pydantic.dev/latest/concepts/validators/#model-validators).
- **Facilitate serialization:** This would make it easier to serialize and save intermediate results using tools like `sqlmodel`.

---

**P.S.** Not that you should take advice from a random internet stranger, but I hope [psx](https://pypi.org/project/psx/) is next on your company’s roadmap! I only know you’ve registered the PyPI name because I started building something similar a couple of months ago and tried to register it myself. Thankfully, I came to my senses and realized that if someone like you (and the rest of the pydantic.dev team) had this on their radar, it was best to get out of your way.

**Comment by samuelcolvin** [comment]
I'm not sure I really understand either either case.

Taking Case 1 as an example, internally pydantic-ai would still be serializing structured as JSON and sending it to the model as a string, and the model would have the option to call any tool with any input it liked.

I don't think we want to add structured inputs:
1. Because making `Agent` generic in 3 parameters makes typing excessively complex
2. There's nothing particularly special we can do - we just serialize the object and pass it the model as JSON
3. I'd like to keep the signature of the `prompt` argument to run as simple as possible to make it easier to add multi-modal support (audio, image, video, files etc.) in future.
