### ISSUE TITLE
How can I deserialize the `response.all_messages_json()` in order to use it for the next query `message_history`s?

### ISSUE THREAD

**Issue by lnxpy** [pydantic/pydantic-ai#208]
Consider a Redis key available with the initial value of `[]`. I'm storing the `response.all_messages_json()` every time I make a query. Only the first time everything works and the message history will be put into the database. Next time when I try to retrieve the history and make a new query based on that history, the system breaks. Here is an example of a message history retrieved from Redist:

```json
[
    {"content": "you are a helpful assistant.", "timestamp": "2024-12-10T18:58:25.794340Z", "role": "system"},
    {"content": "hello", "timestamp": "2024-12-10T18:58:25.794340Z", "role": "user"},
]
```

Traceback:
```
AttributeError: 'dict' object has no attribute 'role'
```

I assume I need to deserialize the retrieved history to some `MessageHistory` object thing, but I can't find it.

**Comment by sydney-runkle** [comment]
@Inxpy,

Perhaps you're looking for `messages.Message`? Specifically:

```py
Message = Union[SystemPrompt, UserPrompt, ToolReturn, RetryPrompt, ModelTextResponse, ModelStructuredResponse]
"""Any message send to or returned by a model."""
```

**Comment by lnxpy** [comment]
Thank you for your response, @sydney-runkle!

I've already looked into it, but it's just a type and I guess I can't go like:
```python
response = await agent.run(
    request.message,
    message_history=[Message(**i) for i in chat_history],
)
```

**Comment by samuelcolvin** [comment]
Use 

https://github.com/pydantic/pydantic-ai/blob/08808eb78616913ec8d305205a75774cb34404ac/pydantic_ai_slim/pydantic_ai/messages.py#L203

```py
MessagesTypeAdapter.validate_python(messages)
```
