### ISSUE TITLE
Gemini 2.0 is out, let's support it

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic-ai#216]
https://blog.google/products/gemini/google-gemini-ai-collection-2024/

Should be relatively simple to test if it works. No idea how much work it'll require to support it, but hopefully none.

**Comment by janas-adam** [comment]
tried [gemini-2.0-flash](https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash) with simply extended literal GeminiModelName
-> got 404 from _`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent`_

```
{
  "error": {
    "code": 404,
    "message": "models/gemini-2.0-flash is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.",
    "status": "NOT_FOUND"
  }
}
```

**Comment by sydney-runkle** [comment]
Done :)
