### ISSUE TITLE
[Packaging issu?]Anthropic is still not supported.

### ISSUE THREAD

**Issue by neptune-v** [pydantic/pydantic-ai#237]
Hi,

I am following the docs to install for Anthropic:
`pip install 'pydantic-ai-slim[anthropic]'`

And I get the following:
```
Collecting pydantic-ai-slim[anthropic]
  Downloading pydantic_ai_slim-0.0.12-py3-none-any.whl.metadata (2.6 kB)
WARNING: pydantic-ai-slim 0.0.12 does not provide the extra 'anthropic'
```

And `pydantic_ai_slim/pydantic_ai/models/anthropic.py` is not being installed.

Please help!!

Thanks in advance!!

**Comment by samuelcolvin** [comment]
We haven't made a release since anthropic was merged as we're working on refactoring how messages are handled, see #232.

We'll do a release today or tomorrow.
