### ISSUE TITLE
Current date & time unawareness as input parameters

### ISSUE THREAD

**Issue by tpotjj** [pydantic/pydantic-ai#245]
Hi team,

First of all, this library is amazing!
This looks 75% similar to what I've built myself in my LLM/AI project, but more scalable and simple, amazing job!

Here is my problem, it looks like the LLM (gpt-4) is completely aware of the current date & time, if I prompt this in the UI, it responds correctly, when I use the API, it responds correctly, but when I try to use pydantic-ai, it responds with a date somewhere in 2022 (I asked this question yesterday, btw).

```Python
@assistant_agent.tool
async def fetch_events(ctx: RunContext[AssistantDependencies], start_datetime: str, end_datetime: str) -> str:
    """Fetches events."""
    print("START DATE", start_datetime)
    print("END DATE", end_datetime)
```

<img width="664" alt="Screenshot 2024-12-13 at 20 40 56" src="https://github.com/user-attachments/assets/dc7c3d6f-523d-4c3c-88e5-32cb5d4f5745" />

I've tried to add more context to the Agent, both in the `Dependencies` and in the `system_prompt`, but this didn't make it much better.

```Python
@dataclass
class AssistantDependencies:
    user: User = Field(description="User object")
    current_datetime: str = Field(description="The current date and time in ISO 8601 format")

assistant_agent = Agent(
    model=model,
    system_prompt=f"You are a helpfull assistant. Today is {datetime.now().strftime('%Y-%m-%d')}.",
)

deps = AssistantDependencies(user=user, current_datetime=datetime.now().isoformat())
result = await assistant_agent.run(text, deps=deps) 
```

Any idea on how to 'make this work'? It's mainly that the `start_datetime` & `end_datetime` have wrong values as input.

**Comment by samuelcolvin** [comment]
This works fine for me every time.

```py
from datetime import date

from pydantic_ai import Agent


assistant_agent = Agent(
    model='openai:gpt-4o',
    system_prompt=f'You are a helpful assistant. Today is {date.today():%Y-%m-%d}.',
)

for i in range(10):
    result = assistant_agent.run_sync('What date is it today?')
    print(f'{i}: {result.data}')
```

Output:

```
0: Today is December 14, 2024.
1: Today is 2024-12-14.
2: Today's date is December 14, 2024.
3: Today is December 14, 2024.
4: Today is December 14, 2024.
5: Today is 2024-12-14.
6: Today's date is December 14, 2024.
7: Today's date is December 14, 2024.
8: Today is December 14, 2024.
9: Today's date is December 14, 2024.
```

If you can provide an MRE with the problem, happy to investigate.
