### ISSUE TITLE
Structured output - code output issue

### ISSUE THREAD

**Issue by lazyevalcoder** [pydantic/pydantic-ai#256]
I am trying to give a prompt for simple coding related queries like write a python code to print the first five numbers of Fibonacci series but the code generated does not follow correct format(indentation and lines), hence it is not executing.

Any help/suggestions are greatly appreciated.

![image](https://github.com/user-attachments/assets/7c86e972-b3b6-467a-ace1-42bd8026e839)

**Comment by samuelcolvin** [comment]
It would be much better if you included the code as a code block in your issue, not as a screenshot.

I suspect the problem is that the code in your system prompt is indented by which is confusing the Model.

You're also using a relatively small model, try with OpenAI.

**Comment by lazyevalcoder** [comment]
@samuelcolvin I am sorry, I tried a much better and bigger model and still the same. Here is the code block:

```python
from pydantic_ai import Agent
from pydantic import BaseModel
import nest_asyncio
import json

nest_asyncio.apply()

class MyCodeModel(BaseModel):
    filename: str
    code: str

agent2 = Agent(  
    'qwen2.5-coder:32b-instruct-q5_K_M',
    system_prompt='''
    You are a coding assistant. 
    Use proper indendation and line breaks
    Do not use tags like \n or \t
    ''',  
    result_type = MyCodeModel,
    retries=3
)

result2 = agent2.run_sync('Write a python code to print the first five numbers of fibonacci series and provide the file name')  

print(result2.data)
print(result2.cost())
```

Here is the output:
```
filename='fibonacci.py' code='def fibonacci(n):\n    fib_series = [0, 1]\n    for i in range(2, n):\n        next_value = fib_series[-1] + fib_series[-2]\n        fib_series.append(next_value)\n    return fib_series[:n]\n\n# Calling the function to print first five numbers of fibonacci series\nprint(fibonacci(5))'
Cost(request_tokens=184, response_tokens=203, total_tokens=387, details=None)
```
