### ISSUE TITLE
Timeout support for Model

### ISSUE THREAD

**Issue by datawx** [pydantic/pydantic-ai#264]
Hi Folks,

Would be possible to add a request timeout parameter when creating models or if there is some other way to acheive it?

The issue I have is that I'm doing quite large dataset transformation work using AI (20k/records) and I need to do work in big batches of concurrent threads. I'll often find that running 300 records/api calls (pool size 50) takes about 1 min with openAI but 5 threads will still keep running for 5 mins, eventually giving a timeout error. This means I wait around for 4 mins to eventually get the error when work was completed long ago. It'll only get worse with more data until the entire pool is zombie threads. They seem to finally time out when they hit the requests library limit (my guess). It would be much more performant if we could set a timeout and then decide what to do rather than being left hanging indefinately.

Thanks!

**Comment by sambarnes** [comment]
@datawx this should actually be supported already if you [pass in an OpenAI client](https://ai.pydantic.dev/models/#custom-openai-client) to the model constructor

```python
from openai import AsyncOpenAI

from pydantic_ai import Agent
from pydantic_ai.models.openai import OpenAIModel

client = AsyncOpenAI(
  api_key="...",
  timeout=0.1,
)
model = OpenAIModel('gpt-4o', openai_client=client)
agent = Agent(model)

result = agent.run_sync('Where does "hello world" come from?')
print(result.data)
```

**Comment by datawx** [comment]
Thanks Samuel for the quick response. This worked, and I'm looking forward to the model change in #227 that looks like is going to be very useful when switching out between models.
