### ISSUE TITLE
EndStrategy `early` isn't working

### ISSUE THREAD

**Issue by YourTechBud** [pydantic/pydantic-ai#266]
Currently pydantic ai agents prompt the model once again after a successful tool call as illustrated [on this page](https://ai.pydantic.dev/tools/).

I'm sure this behavior would be helpful especially when we want to multiple tool calls one after the other. But some of us may not want to do that. Maybe, I want to take the raw result of the first tool call and forward it to another agent for summarization. I believe this should be the default behavior when the [EndStrategy](https://ai.pydantic.dev/api/agent/#pydantic_ai.agent.EndStrategy) is `early`.

Also, I didn't see `end_strategy` as one of the parameters that I could pass. Is this not released yet?

**Comment by samuelcolvin** [comment]
That's not what Early exit is for, I guess we should document that.

If your just want to exit on a tool call, just use a structured result type, or wait for #142.
