### ISSUE TITLE
Is it possible to activate json_mode when using openai?

### ISSUE THREAD

**Issue by arjuna-dev** [pydantic/pydantic-ai#275]
I couldn't find info in the docs regarding openai's json_mode. Is it possible to activate it when using openai as the model for an agent?

Thanks!

**Comment by samuelcolvin** [comment]
hi we don't support it explicitly, instead we support structured responses, as described here - https://ai.pydantic.dev/results/.

Internally this uses tool calls.

Can you explain your use case?

**Comment by arjuna-dev** [comment]
Thanks for the reply! 

I am currently working on an app that generates language lessons ([parakeet](https://parakeet.world/)), our current approach relies heavily on open ai's json_mode. We found out that LLMs couldn’t really generate the precise dialogues we needed so our approach is to create a (relatively complex) json with all the needed parts that could can be used in our language lesson and then we use those parts to craete language lesson, it works nicely. Going forward we want to keep using this approach for other use cases.

Could I simply do?:

class LanguageLesson(BaseModel):
    city: Json[Any]

How does pydantic ai's results work udner the hood to "force" the model to answer in a certain format? Are you doing it by prompting the model to coherce it to respond in a certain way? I guess I could fork pydantic ai and add the line of code to use json_mode when using an openai model?

I had another question maybe you can help me with. How does the LLM decide which tool to use? Is tit based on the name of the function? Or is there a field or docstring with a description that the LLM can rely on to decide if this is the need tool?

For example openai has a description key-value pair that specifies when the function should be called, I guess specifying that in the system prompt could also be an option. This is how opanai does it using the description key:


```json
{
    "name": "get_delivery_date",
    "description": "Get the delivery date for a customer's order. Call this whenever you need to know the delivery date, for example when a customer asks 'Where is my package'",
    "parameters": {
        "type": "object",
        "properties": {
            "order_id": {
                "type": "string",
                "description": "The customer's order ID."
            }
        },
        "required": ["order_id"],
        "additionalProperties": false
    }
}
```

**Comment by arjuna-dev** [comment]
hi, thanks for the reply!

So I guess I could do:

```python
class LanguageLesson(BaseModel):
    languageLesson: Json[Any]
```

When you say that internally this uses tools you mean that internally a function is in charge of outputting in the required type? Do you also coherce the LLM with a prompt to answer in a certain format? I guess I could fork pydantic ai and add the code to the openai call to enable json_mode if I needed to?

Our use case is a language learning app ([parakeet](https://parakeet.world/)). We saw that LLMs couldn't generate the  language lessons we wanted in terms of structure so what we do is that we ask the LLM (chatGPT) to generate a specific (more or less complex) JSON with all the language lessons parts (characters, translations, etc.). We then get the data from this structure to create a precisee language lesson structure. This worked nicely so we want to continue using this approach with other use cases.
