### ISSUE TITLE
Assistant message missing after streaming the response

### ISSUE THREAD

**Issue by pietz** [pydantic/pydantic-ai#375]
If I call the all_messages() or new_messages() methods after streaming a response, the latest assistant message is missing.

```python
from pydantic_ai import Agent
import asyncio
from dotenv import load_dotenv
load_dotenv()

async def run():
    agent = Agent("openai:gpt-4o", system_prompt="You're a helpful assistant.")
    
    result1 = await agent.run("Are you ready to help me?")
    print([x.role for x in result1.new_messages()])
    
    # ['user', 'model-text-response']

    async with agent.run_stream("Are you ready to help me?") as result2:
        async for text in result2.stream_text(delta=True):
            pass
    print([x.role for x in result2.new_messages()])
    
    # ['user']


if __name__ == "__main__":
    asyncio.run(run())
```

**Comment by sydney-runkle** [comment]
Hi @pietz,

What version are you using? I think we may have fixed this in the most recent release...

**Comment by pietz** [comment]
@sydney-runkle 0.0.12

**Comment by sydney-runkle** [comment]
Ok, I'm wrong, maybe it's not fixed:

```py
from pydantic_ai import Agent
import asyncio

async def run():
    agent = Agent("gemini-1.5-flash", system_prompt="You're a helpful assistant.")
    
    result1 = await agent.run("Are you ready to help me?")
    print([x.kind for x in result1.new_messages()])
    
    # ['request', 'response']

    async with agent.run_stream("Are you ready to help me?") as result2:
        async for text in result2.stream_text(delta=True):
            pass
    print([x.kind for x in result2.new_messages()])
    
    # ['request']


if __name__ == "__main__":
    asyncio.run(run())
```

**Comment by pietz** [comment]
@sydney-runkle Where can I read more about the reasoning behind the change in `Message` structure? Seems quite confusing at first glance.

**Comment by sydney-runkle** [comment]
@pietz,

Great question. I think this graph will help:

https://ai.pydantic.dev/api/messages/

**Comment by sydney-runkle** [comment]
Ah, this isn't a bug, you just have to use `delta=False`, then you'll get the expected result.

Closing as resolved for now, feel free to ping me if you have additional follow up questions!

**Comment by pietz** [comment]
Interesting, I don't really the semantic connection between how I retrieve the data chunks and what the response object looks like afterwards. It seems more logical to me that in the end it should look the same. If it's a technical limitation, I get it. I think I can work around it by using `delta=False`.

Thank you
