### ISSUE TITLE
Isn't a foobar a bad choice for examples?

### ISSUE THREAD

**Issue by snqb** [pydantic/pydantic-ai#490]
Hi. Thank you very much for all the work you've done. I really like your approach to agency.
But going through documentation examples, I've come across several Foobar models in examples.
If to think, it's very confusing why apples and carrots as comments, why x,y,z(yeah, foobar, but do we have to?) as variables etc.

![{2D2014CC-BC94-4451-B6D6-7B5ED0027ED5}](https://github.com/user-attachments/assets/62eafb5e-f1c5-4a6a-b67b-4098bb5d6ebb)

**Comment by sydney-runkle** [comment]
Hi @snqb,

Great question! Yes, we should definitely improve this. I'm happy to do a docs pass to improve example relevance.

**Comment by sydney-runkle** [comment]
So I guess given the above, I'm going to close this for now. Maybe if we get more feedback in this vein, we could reconsider!
