### ISSUE TITLE
Huggingface API Compatibility Inquiry

### ISSUE THREAD

**Issue by viasky657** [pydantic/pydantic-ai#493]
I am curious to know if it is possible to utilize custom models or Huggingface model API endpoints through a custom API url similarly to how the Pydantic program handles Openrouter API calls as demonstrated in the "Models" section of the Pydantic documentation. Thank you for your time and consideration.

**Comment by samuelcolvin** [comment]
See #398, sounds like it should be possible soon once we work around a bug in hugging face's TGI project.
