### ISSUE TITLE
Import error when installed with pipenv: Package's internal absolute imports fail

### ISSUE THREAD

**Issue by eliza-guseva** [pydantic/pydantic-ai#502]
Hello!

I am very excited to start working with `pydantic-ai` and wanted to report an issue I've encountered. I'm not entirely sure if this is more relevant to pydantic or pipenv, but I thought it would be helpful to report it.

## Issue Description
When installed via pipenv, the package fails to find path for example `from pydantic_ai import Agent` says that Agent doesn't exist. The same imports work when the package is installed directly via pip.

## Environment Details
Tested scenarios:
- ✅ Works: Python 3.11.7 with pip
- ✅ Works: Python 3.12 with pip
- ❌ Fails: Python 3.12 with pipenv

## Steps to Reproduce
1. Create a pipenv environment with Python 3.12
2. Install package: `pipenv install pydantic-ai`
3. Try to import: `from pydantic_ai import Agent`
4. Import fails 

## Root Cause
The package uses absolute imports internally (`from pydantic_ai import ...`), so even if I do `from pydantic_ai.agent import Agent` it fails. I think it might be dependent on specific Python path configurations. While this works with pip's installation structure, it fails with pipenv. Which is honestly a mystery for me.

## Current Workaround
The issue can be worked around by adding the parent directory to sys.path:
```python
import os
import sys
import pydantic_ai
sys.path.append(os.path.dirname(os.path.dirname(pydantic_ai.__path__[0])))
import importlib
importlib.reload(pydantic_ai)

**Comment by samuelcolvin** [comment]
Humm, I can't reproduce.

I don't use pipenv, so to isolate things, I ran the following inside docker (run with `docker run --rm -it ubuntu:latest`):
```bash
apt update
apt install python3.12 python3-pip -y
python3.12 -m pip install pipenv --break-system-packages
pipenv install pydantic_ai
pipenv run python -c 'import pydantic_ai;print(pydantic_ai.__version__)'
0.0.14
pipenv run python -c 'from pydantic_ai import Agent;print(Agent)'
<class 'pydantic_ai.agent.Agent'>
```

If you can provide an MRE that points to a problem with pydantic-ai, I can try to help, otherwise I think we'll have to put this down to a quirk of packaging.

**Comment by eliza-guseva** [comment]
Thanks for looking into it!
I think it might have go down as a quick of packaging.
It only reproduces for me in my dev environment with (maybe specifically mine) mac os. I also tried running it with the same version of pipenv and pydantic-ai on docker's ubuntu. And it works completely fine. I don't think I would be able to provide a reasonable MRE for this.
