### ISSUE TITLE
Functionality to Define Multi-Agent Graphs and Workflows

### ISSUE THREAD

**Issue by izzyacademy** [pydantic/pydantic-ai#529]
@samuelcolvin and team. Thank you for the amazing work on the framework so far.

After taking a look at the codebase and documentation, there is currently no mechanism to define nodes and edges (static or dynamic) in advanced workloads where there are multiple agents involved.

Is there a plan to add this capability in the near future?

I like the capability of defining the nodes and edges either statically via state graphs or dynamically in Langgraph using the Command feature [1]. CrewAI also has something similar added recently as flows [2] 

I was looking to see when something similar is planned for PydanticAI. 

This is necessary when building real life workflows in productions where the hand off from one agent or node to another could be static in some scenarios and dynamic in other scenarios based on what is happening between transitions.

I would love to hear your thoughts.

References
[1] https://langchain-ai.github.io/langgraph/concepts/low_level/#command
[2] https://docs.crewai.com/concepts/flows

**Comment by izzyacademy** [comment]
I like the code sample in #300 by @ishswar but I think if you have scenarios where the selection of the next node is not fixed or the next node is actually multiple nodes, this may not really work well if you have to run the subsequent nodes in parallel and then wait on them to complete before the next agent picks up from the multiple agents that just finished.

**Comment by samuelcolvin** [comment]
Full support for graphs is coming too, see https://github.com/pydantic/pydantic-ai/pull/528 and https://github.com/pydantic/pydantic-ai/pull/539.
