### ISSUE TITLE
Logfire icon error / typo on PydanticAI docs homeage

### ISSUE THREAD

**Issue by alexander-zuev** [pydantic/pydantic-ai#543]
![Screenshot 2024-12-25 at 2 17 30 PM](https://github.com/user-attachments/assets/88fc04d5-29be-4e8e-8014-8f66683809fe)

On the docs [homepage](https://ai.pydantic.dev/) -> the logfire icon is not displaying correctly.

**Comment by samuelcolvin** [comment]
It'll be because your css is cached, if you clear the cache it should work correctly.
