### ISSUE TITLE
Use Griffe's public API

### ISSUE THREAD

**Issue by pawamoy** [pydantic/pydantic-ai#548]
Any reason you're importing from the internal API?

https://github.com/pydantic/pydantic-ai/blob/b9ec73fe8d47d7859dbf7eefbade198f3cc0eb34/pydantic_ai_slim/pydantic_ai/_griffe.py#L7-L8

You're exposing yourself to breakages if I change these internals :sweat_smile:
Public equivalent:

```python
from griffe import DocstringSectionKind, Docstring, Object as GriffeObject 
```

If it's to avoid loading too many things, note that `_griffe.models` imports a lot of stuff anyway:

```python
from _griffe.c3linear import c3linear_merge
from _griffe.docstrings.parsers import DocstringStyle, parse
from _griffe.enumerations import Kind, ParameterKind, Parser
from _griffe.exceptions import AliasResolutionError, BuiltinModuleError, CyclicAliasError, NameResolutionError
from _griffe.expressions import ExprCall, ExprName
from _griffe.logger import logger
from _griffe.mixins import ObjectAliasMixin
```

**Comment by samuelcolvin** [comment]
I'd love to use public APIs only. 

PR welcome to fix it, otherwise I'll try soon.
