### ISSUE TITLE
Longer text returns may seem to be missing at the end.

### ISSUE THREAD

**Issue by blackwhite084** [pydantic/pydantic-ai#552]
class QaResult(BaseModel):
    answer: str = Field(description="Answer to question, Markdown format")
    mermaid: str = Field(description="")
    

This answer may not be finished yet

**Comment by sydney-runkle** [comment]
Hi @blackwhite084,

Thanks for your question. We'll need some more info to help you troubleshoot. What sort of prompt are you using? Could you show us an example of cutoff output? Perhaps you're hitting some sort of output token limit?

Going to close this for now until we have an MRE, but happy to help you once we get some more info.
