### ISSUE TITLE
[chat_app example] the message are in another order when refreshing the page

### ISSUE THREAD

**Issue by scenaristeur** [pydantic/pydantic-ai#561]
following fastapi_chatapp https://ai.pydantic.dev/examples/chat-app/

first i send 2 messages
![Screenshot 2024-12-29 at 00-12-55 Chat App](https://github.com/user-attachments/assets/368e5ff6-ebae-4fea-acd3-310206bd8661)
then i refresh the browser with F5 and the message are not in the good order

![Screenshot 2024-12-29 at 00-13-13 Chat App](https://github.com/user-attachments/assets/76ef08fc-36c9-4103-85f2-7ee66b7e8655)
perhaps the "ORDERBY ID" is not a good choice, shouldn'be order by timestamp ?

![2024-12-29_00-13](https://github.com/user-attachments/assets/d34fde8f-91c2-4cf5-b9ef-f9d3828e249d)

**Comment by samuelcolvin** [comment]
Thanks, looks like they were in the reverse order, fixed in #569.
