### ISSUE TITLE
Add `message_limit` (number of model messages) and `cost_limit` to `run()` methods

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic-ai#70]
To mitigate the risk that an agent gets into an infinite loop.

**Comment by fatelei** [comment]
i want to have a try

**Comment by moustaphacheikh** [comment]
hey, is this issue solved in #409  ? or is it still open ?

**Comment by samuelcolvin** [comment]
Yes, this was solved in #409.
