### ISSUE TITLE
Should we drop/change `CallContext`?

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic-ai#80]
background: feedback from a few people has been that the `CallContext[MyDeps]` pattern of dependency injection is somewhat complicated.

We have a few options:
* keep what we have now, but document it better
* remove `CallContext`
* some other way of injecting dependenices, explored below

---

### Here's what we have now

(some imports omitted for brevity)

```py
from pydantic_ai import Agent, CallContext

@dataclass
class MyDeps:
    customer_id: int
    db: DatabaseConn

agent = Agent('openai:gpt-4o', deps_type=MyDeps)

@agent.retriever_plain  # retriever_plain doesn't take deps/context
def roll_die(sides: int) -> str:
    """Roll a six-sided die and return the result."""
    return str(random.randint(1, sides))


@agent.retriever
async def customer_balance(ctx: CallContext[MyDeps], include_pending: bool) -> str:
    balance = await ctx.deps.db.customer_balance(id=ctx.deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

The point is:
* `@agent.retriever_plain` can have any parameters, they're all parsed and used to create the schema passed to the LLM, then filled by the tool call data from the LLM
* `@agent.retriever` is required (via [`Concatenate`](https://docs.python.org/3/library/typing.html#typing.Concatenate)) to take `CallContext[AgentDeps]` as it's first argument, other arguments are parsed and passed to the LLM the same as `retriever_plain`
* if `CallContext` or `CallCointext[...]` is found in any position other than as the first argument of `retriever`, we raise an error at runtime. This makes sure that the developer should never confuse dependencies they pass to the run with dependencies invented by the LLM, if they stick to the `CallCointext[...]` pattern

**The real question is whether `ctx: CallContext[MyDeps] ... ctx.deps` is confusing enough to change?**

### 1. Alternative - no `CallContext`

We could switch to just

```py
@agent.retriever
async def customer_balance(deps: MyDeps, include_pending: bool) -> str:
    balance = await deps.db.customer_balance(id=deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

(The other attributes of `CallContext`, `retry` and `tool_name` are very rarely used and could be accessed via contextvars when people do want to use them)

This involvers less typing complexity, and less code. 

But it risks people accidentally using

```py
@agent.retriever_plain
async def customer_balance(deps: MyDeps, include_pending: bool) -> str:
    balance = await deps.db.customer_balance(id=deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

In this case, although type checking will pass, `deps` is NOT injected by PydanticAI, but instead included in the schema for the LLM to generate. In this case, we could never create a `DatabaseConn` from JSON, so we're probably safe, but deps could be something like `dataclass MyDeps(url: str, api_key: str)` which could be generated by the LLM.

We also can't as easily check if the type of any parameter matches the deps type, since there are cases where the type you use for  deps is also the type used for a paramter (e.g. if your deps type was just `str`).

We could check if the name of the parameter was `deps` or `dependencies` and warn/error on that. Is that good enough?

### 2. Alternative - `Annotated[MyDeps, Inject]`

The idea would be you have to use `Annotated[MyDeps, Inject]` to access deps.

```py
@agent.retriever
async def customer_balance(deps: Annotated[MyDeps, Inject], include_pending: bool) -> str:
    balance = await deps.db.customer_balance(id=deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

Disadvantages:
* more typing (in both senses)
* doesn't avoid the case I showed above with `@agent.retriever_plain`, just makes it a bit less likely
* no type checking errors if you use `@agent.retriever ... deps: MyDeps`, just an import time error about how you need to use `Annotated[MyDeps, Inject]` 🤮 

### 3. Alternative - `deps: MyDeps = Inject`

Something like 

```py
@agent.retriever
async def customer_balance(deps: MyDeps = Inject, include_pending: bool) -> str:
    balance = await deps.db.customer_balance(id=deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

The problem with this is either:
* you have `deps` as the first argument, then all subsequent arguments need to have defaults
* or you have `deps` later and we loose the typing guarantees offered by `Concatenate` that the deps type matches the `AgentDeps` generic type from the Agent

---

I think I discount options 2 and 3, so unless someone has some other bright idea, we'll either need to stick with what we have, or switch to option 1.

**Comment by davidhewitt** [comment]
Can potentially overload the decorator, and require an argument to make an explicit choice of deps

```python
@agent.retriever(None)  # plain receiver
def roll_die(sides: int) -> str:
    ...

@agent.retriever(MyDeps)  # contextual receiver
async def customer_balance(ctx: CallContext[MyDeps], include_pending: bool) -> str:
    ...

@agent.retriever(tuple[()])  # contextual receiver with nothing injected, maybe?
async def customer_balance(ctx: CallContext[tuple[()]], include_pending: bool) -> str:
    ...
```

**Comment by davidhewitt** [comment]
Could even go further here and make the `retry` and `tool_name` stuff that can be injected as part of the `Deps` type (or a tuple), and then you wouldn't need the `CallContext` wrapper?

```python
@agent.retriever(None)  # no deps
def roll_die(sides: int) -> str:
    ...

@agent.retriever(MyDeps)  # deps
async def customer_balance(deps: MyDeps, include_pending: bool) -> str:
    ...

@agent.retriever(tuple[MyDeps, ToolName])  # deps and tool name
async def customer_balance(deps: MyDeps, tool_name: ToolName, include_pending: bool) -> str:
    ...
```

Disclaimer: haven't tried typing here.

**Comment by adriangb** [comment]
I like the current system *but* would rename it to `FromContext`.

One alternative not discussed: always make it the first argument if you ask for it or not. Then no market is needed and there's no confusion. But you do have to specify it even if you don't need it.

**Comment by samuelcolvin** [comment]
Consensus from speaking to quite a lot of people is that the current system is the best (least bad) solution. The only question is what should we call `CallContext`?

My suggestion would be `Inject`, so usage is

```py
@agent.retriever
async def customer_balance(ctx: Inject[MyDeps], include_pending: bool) -> str:
    balance = await ctx.deps.db.customer_balance(id=ctx.deps.customer_id, include_pending=include_pending)
    return f'${balance:.2f}'
```

The other option is to stick with `CallContext` for now, it's not too hard to change it in the future and still support the old name, with a deprecation warning.

**Comment by samuelcolvin** [comment]
Consensus from speaking to quite a lot of people is that the current system is the best (least bad) solution. The only question is what should we call `CallContext`?

After discussing this with @dmontagu we've decided to go with `RunContext` for now.
